CREATE USER bank
  IDENTIFIED BY bank
  DEFAULT TABLESPACE TBS_bank_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT CONNECT TO bank;
  ALTER USER bank DEFAULT ROLE ALL;
  GRANT CREATE DATABASE LINK TO bank;
  GRANT CREATE TRIGGER TO bank;
  GRANT DEBUG CONNECT SESSION TO bank;
  GRANT SELECT ANY TABLE TO bank;
  GRANT CREATE TABLE TO bank;
  GRANT CREATE PROCEDURE TO bank;
  GRANT CREATE SEQUENCE TO bank;
  GRANT CREATE VIEW TO bank;
  grant select, update on sys.source$ to bank;
  ALTER USER bank QUOTA UNLIMITED ON TBS_bank_DATA;
  ALTER USER bank QUOTA UNLIMITED ON TBS_bank_IDX;