---TRIGGER. (BLOQUE DE CODIGO QUE SE EJECUTA AUTOMATICAMENTE)
-------  MANTENER LA INTEGRIDAD REFERENCIAL DE LAS TBS
-------  TENER EL CONTROL DE CAMBIOS DE LA INFORMACION.
--- EVENTO: INSERSION, ACTUALIZACION, ELIMINACION
---ACCION: PROGRAMACION DE INSERTS, UPDATES, DELETES PARA OTROS RECURSOS
--- UN TRIGGER : ES UN EVENTO QUE SE EJECUTA AUTOMATICAMENTE, CADA VEZ
--- QUE SE REALIZA UNA ACCION.
---NO TIENE PARAMETROS DE ENTRADA/SALIDA


--SINRTAXIS.


