REM INSERTING into BANK.CF_INTERESTS
SET DEFINE OFF;
Insert into BANK.CF_INTERESTS (CODE,INT_DESCRIPTION,TYPE_INTEREST,TYPE_EVALUATION,START_DATE,END_DATE,STATUS,START_USER_CODE,END_USER_CODE,TRAN_ID) values ('PAGO_INT_PORC','INTERES PAGADO POR MANTENIMIENTO DE CTTA DEL CLIENTE','PAGO','PORCENTAGE',to_date('26-10-2017 00:07:28','DD-MM-RRRR HH24:MI:SS'),to_date('31-12-9999 00:00:00','DD-MM-RRRR HH24:MI:SS'),'A','BANK','BANK',-13);
Insert into BANK.CF_INTERESTS (CODE,INT_DESCRIPTION,TYPE_INTEREST,TYPE_EVALUATION,START_DATE,END_DATE,STATUS,START_USER_CODE,END_USER_CODE,TRAN_ID) values ('COBRO_INT_PORC','INTERES COBRADO POR MANTENIMIENTO DE CTTA','COBRO','PORCENTAGE',to_date('26-10-2017 00:07:28','DD-MM-RRRR HH24:MI:SS'),to_date('31-12-9999 00:00:00','DD-MM-RRRR HH24:MI:SS'),'A','BANK','BANK',-13);
Insert into BANK.CF_INTERESTS (CODE,INT_DESCRIPTION,TYPE_INTEREST,TYPE_EVALUATION,START_DATE,END_DATE,STATUS,START_USER_CODE,END_USER_CODE,TRAN_ID) values ('PAGO_INT_FIJO','INTERES PAGADO POR GANANCIA A LA CCTA DE CLIENTE','PAGO','MONTO_FIJO',to_date('25-10-2017 23:42:40','DD-MM-RRRR HH24:MI:SS'),to_date('31-12-2017 23:42:51','DD-MM-RRRR HH24:MI:SS'),'A','BANK','BANK',-14);
commit;
