--------------------------------------------------------
--  DDL for Table CF_INTERESTS
--------------------------------------------------------

  CREATE TABLE "BANK"."CF_INTERESTS" 
   (	"CODE" VARCHAR2(50 BYTE), 
	"INT_DESCRIPTION" VARCHAR2(100 BYTE), 
	"TYPE_INTEREST" VARCHAR2(50 BYTE), 
	"TYPE_EVALUATION" VARCHAR2(50 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(5 BYTE), 
	"START_USER_CODE" VARCHAR2(50 BYTE), 
	"END_USER_CODE" VARCHAR2(50 BYTE), 
	"TRAN_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_BANK_DATA" ;
