--------------------------------------------------------
--  File created - Saturday-October-28-2017   
--------------------------------------------------------
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/CF_INTERESTS.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/CF_INTEREST_EVAL.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TR_ACCOUNT.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TR_DAILY.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TR_ERROR_LOG.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/SEQ_ACCOUNT.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/SEQ_DAILY.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/SEQ_ERROR_LOG.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/SEQ_INTEREST_EVAL.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/SEQ_TRAN_ID.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/CF_INTERESTS_DATA_TABLE.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/CF_INTEREST_EVAL_DATA_TABLE.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TR_ACCOUNT_DATA_TABLE.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TR_DAILY_DATA_TABLE.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TR_ERROR_LOG_DATA_TABLE.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/PK_INTEREST_EVAL_ID.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/PK_DAILY_ID.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/PK_INTEREST_CODE.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/PK_ACCOUNT_ID.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/GET_ACCOUNT_DATA.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/GET_SUM_TOTAL.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/INSERT_TR_ACCOUNT.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/INSERT_TR_ACCOUNT01.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/BL_PROCESS_ACCOUNT.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/BL_PROCESS_ACCOUNT_SVA.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/BL_PROCESS_INTEREST.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/GLOBAL_VARIABLE.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/PS_TR_ACCOUNT.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/PS_TR_DAILY.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/PS_TR_ERROR_LOG.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TX_TR_ACCOUNT.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TX_TR_DAILY.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TX_TR_ERROR_LOG.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/BL_PROCESS_ACCOUNT_1.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/BL_PROCESS_ACCOUNT_SVA_1.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/BL_PROCESS_INTEREST_1.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/PS_TR_ACCOUNT_1.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/PS_TR_DAILY_1.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/PS_TR_ERROR_LOG_1.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TX_TR_ACCOUNT_1.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TX_TR_DAILY_1.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TX_TR_ERROR_LOG_1.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TR_ACCOUNT_CONSTRAINT.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/CF_INTERESTS_CONSTRAINT.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TR_ERROR_LOG_CONSTRAINT.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/TR_DAILY_CONSTRAINT.sql
@/Users/abel/DocAbel/CursoCertificacionUPB/ALL_PACKAGES/CF_INTEREST_EVAL_CONSTRAINT.sql
