--------------------------------------------------------
--  DDL for Table TR_DAILY
--------------------------------------------------------

  CREATE TABLE "BANK"."TR_DAILY" 
   (	"DAILY_ID" NUMBER(15,0), 
	"ACCOUNT_ID_ORIGIN" NUMBER(15,0), 
	"ACCOUNT_ID_DESTIN" NUMBER(15,0), 
	"AMOUNT" NUMBER(15,2), 
	"TYPE_TRANSACTION" VARCHAR2(50 BYTE), 
	"START_TRAN_DATE" DATE, 
	"START_USER_CODE" VARCHAR2(50 BYTE), 
	"END_TRAN_DATE" DATE, 
	"END_USER_CODE" VARCHAR2(50 BYTE), 
	"TRAN_ID" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_BANK_DATA" ;
