--------------------------------------------------------
--  DDL for Table TR_ERROR_LOG
--------------------------------------------------------

  CREATE TABLE "BANK"."TR_ERROR_LOG" 
   (	"ERROR_LOG_ID" NUMBER(15,0), 
	"TRAN_ID" NUMBER(15,0), 
	"ERROR_LINE" VARCHAR2(50 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"ERROR_SOURCE" VARCHAR2(4000 BYTE), 
	"PROCESS_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_BANK_DATA" ;
