CREATE USER WEBUSER
IDENTIFIED BY webuser
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK;
GRANT CONNECT TO WEBUSER;
ALTER USER WEBUSER QUOTA UNLIMITED ON USERS;

-- Grant/Revoke object privileges 
grant select on BANK.TR_ACCOUNT to WEBUSER;
grant select on BANK.TR_DAILY to WEBUSER;
grant select on BANK.TR_ERROR_LOG to WEBUSER;
grant execute on BANK.TX_PUBLIC_WEB to WEBUSER;
